---
- name: Determine public node IPs
  set_fact:
    vlan_public_node_ips: "{{ groups[vlan_group] | map('extract', hostvars, ['ansible_host']) | difference([ansible_host]) | list }}"
    vlan_net: "{{ vlan_ip }}/{{ vlan_netmask }}"

- name: Create /etc/network/if-down.d
  file:
    path: /etc/network/if-down.d
    state: directory
    mode: '0755'

- name: Create if-down config
  template:
    src: stop.j2
    dest: "/etc/network/if-down.d/{{ vlan_interface }}"
    mode: '0755'
  notify: Restart VLAN service

- name: Create /etc/network/if-up.d
  file:
    path: /etc/network/if-up.d
    state: directory
    mode: '0755'

- name: Create if-up config
  template:
    src: start.j2
    dest: "/etc/network/if-up.d/{{ vlan_interface }}"
    mode: '0755'
  notify: Restart VLAN service

- name: Create ports config
  template:
    src: ports.j2
    dest: "/etc/network/{{ vlan_interface }}-ports"
    mode: '0755'
  notify: Reload VLAN service
