---
- name: Slurp /etc/network/interfaces file
  slurp:
    src: /etc/network/interfaces
  register: network_interfaces_file

- name: Set network management
  set_fact:
    vlan_network_management: "{{ \
    ('ifupdown has been replaced by netplan' in (network_interfaces_file['content'] | b64decode)) \
    | ternary('netplan','ifupdown') \
    }}"
