---
- name: Verify hosts can ping each other using VLAN IPs
  hosts: all
  tasks:
    - name: Ping all VLAN members
      shell: "ping -c 1 {{ item }}"
      changed_when: no
      with_items: "{{ groups['all'] | map('extract', hostvars, 'vlan_ip') | list }}"
