---
- name: Verify hosts can ping each other using VLAN IPs
  hosts: all
  tasks:
    - name: Ping all VLAN members
      shell: "ping -c 1 {{ item }}"
      changed_when: no
      retries: 5
      delay: 10
      register: result
      until: result.rc == 0
      with_items: "{{ groups['all'] | map('extract', hostvars, 'vlan_ip') | list }}"
    - name: Reboot hosts
      reboot:
        reboot_timeout: 30
    - name: Ping all VLAN members
      shell: "ping -c 1 {{ item }}"
      retries: 5
      delay: 10
      register: result
      until: result.rc == 0
      changed_when: no
      with_items: "{{ groups['all'] | map('extract', hostvars, 'vlan_ip') | list }}"
